StartFunc
mymmrac/telego pull request #110
Opened 2023-06-08 14:20 UTC by abakum

# :speech_balloon: Description

[//]: # (Please include a summary of the change, if it was related to the issue specify it)

...

## :monocle_face: Type of change

[//]: # (Please select options that are relevant, and delete others)

- [+] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (changes in comments, .md files or other docs)
- [ ] Test update (changes in existing test cases)

# :clipboard: Checklist

[//]: # (Please make sure to check all tasks)

- [ ] My code follows the [style guidelines](../docs/CONTRIBUTING.md#art-style-guidelines) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] Feature or fix that I was working on is in "[releasable](../docs/CONTRIBUTING.md#always-releasable)" state

2023-06-08 17:13 UTC, abakum commented
If you replace nil with err in return, then after pressing Ctrl-C will be:
Stopping...
2023/06/08 17:12:52 Permanent error when accepting new connections: failed to accept connection: Tunnel closed
StopWebhook done
panic: close of closed channel

goroutine 14 [running]:
github.com/mymmrac/telego.(*Bot).StartWebhook(0xc0000f8770, {0x0, 0x0})
        Y:/src/telego/webhook.go:195 +0x156
main.main.func2()
        Y:/src/telego/examples/ngrok/main.go:75 +0x25
created by main.main
        Y:/src/telego/examples/ngrok/main.go:74 +0x6bd
exit status 2

2023-06-11 07:45 UTC, abakum commented
customLoger
![2023-06-11_10-44-34](https://github.com/mymmrac/telego/assets/18271863/d14ad0d7-7c7f-4460-ba87-485befadc784)

2023-06-11 10:53 UTC, mymmrac requested changes

2023-06-11 11:36 UTC, abakum commented on examples/custom_logger/main.go
Please do not use blue. On black it badly look

2023-07-02 18:31 UTC, closed without merging